[project]
name = "linkedex"
version = "1.0.0"
description = "A linkedin scraper integrated with flask that scrapes user profiles based on search query."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"